# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_BotInteractor', [dirname(__file__)])
        except ImportError:
            import _BotInteractor
            return _BotInteractor
        if fp is not None:
            try:
                _mod = imp.load_module('_BotInteractor', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _BotInteractor = swig_import_helper()
    del swig_import_helper
else:
    import _BotInteractor
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class BotInteractor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BotInteractor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BotInteractor, name)
    __repr__ = _swig_repr
    __swig_getmethods__["GoThroughPath"] = lambda x: _BotInteractor.BotInteractor_GoThroughPath
    if _newclass:
        GoThroughPath = staticmethod(_BotInteractor.BotInteractor_GoThroughPath)
    __swig_getmethods__["StartGame"] = lambda x: _BotInteractor.BotInteractor_StartGame
    if _newclass:
        StartGame = staticmethod(_BotInteractor.BotInteractor_StartGame)
    __swig_getmethods__["GoToPoint"] = lambda x: _BotInteractor.BotInteractor_GoToPoint
    if _newclass:
        GoToPoint = staticmethod(_BotInteractor.BotInteractor_GoToPoint)
    __swig_getmethods__["GetArea"] = lambda x: _BotInteractor.BotInteractor_GetArea
    if _newclass:
        GetArea = staticmethod(_BotInteractor.BotInteractor_GetArea)
    __swig_getmethods__["FindPlayerPath"] = lambda x: _BotInteractor.BotInteractor_FindPlayerPath
    if _newclass:
        FindPlayerPath = staticmethod(_BotInteractor.BotInteractor_FindPlayerPath)
    __swig_getmethods__["PulseCheck"] = lambda x: _BotInteractor.BotInteractor_PulseCheck
    if _newclass:
        PulseCheck = staticmethod(_BotInteractor.BotInteractor_PulseCheck)

    def __init__(self):
        this = _BotInteractor.new_BotInteractor()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _BotInteractor.delete_BotInteractor
    __del__ = lambda self: None
BotInteractor_swigregister = _BotInteractor.BotInteractor_swigregister
BotInteractor_swigregister(BotInteractor)

def BotInteractor_GoThroughPath():
    return _BotInteractor.BotInteractor_GoThroughPath()
BotInteractor_GoThroughPath = _BotInteractor.BotInteractor_GoThroughPath

def BotInteractor_StartGame(login, password, char_name):
    return _BotInteractor.BotInteractor_StartGame(login, password, char_name)
BotInteractor_StartGame = _BotInteractor.BotInteractor_StartGame

def BotInteractor_GoToPoint(*args):
    return _BotInteractor.BotInteractor_GoToPoint(*args)
BotInteractor_GoToPoint = _BotInteractor.BotInteractor_GoToPoint

def BotInteractor_GetArea():
    return _BotInteractor.BotInteractor_GetArea()
BotInteractor_GetArea = _BotInteractor.BotInteractor_GetArea

def BotInteractor_FindPlayerPath(end):
    return _BotInteractor.BotInteractor_FindPlayerPath(end)
BotInteractor_FindPlayerPath = _BotInteractor.BotInteractor_FindPlayerPath

def BotInteractor_PulseCheck():
    return _BotInteractor.BotInteractor_PulseCheck()
BotInteractor_PulseCheck = _BotInteractor.BotInteractor_PulseCheck

# This file is compatible with both classic and new-style classes.


