# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_WowInteractionUtils', [dirname(__file__)])
        except ImportError:
            import _WowInteractionUtils
            return _WowInteractionUtils
        if fp is not None:
            try:
                _mod = imp.load_module('_WowInteractionUtils', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _WowInteractionUtils = swig_import_helper()
    del swig_import_helper
else:
    import _WowInteractionUtils
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Vector3(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vector3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vector3, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _WowInteractionUtils.Vector3_x_set
    __swig_getmethods__["x"] = _WowInteractionUtils.Vector3_x_get
    if _newclass:
        x = _swig_property(_WowInteractionUtils.Vector3_x_get, _WowInteractionUtils.Vector3_x_set)
    __swig_setmethods__["y"] = _WowInteractionUtils.Vector3_y_set
    __swig_getmethods__["y"] = _WowInteractionUtils.Vector3_y_get
    if _newclass:
        y = _swig_property(_WowInteractionUtils.Vector3_y_get, _WowInteractionUtils.Vector3_y_set)
    __swig_setmethods__["z"] = _WowInteractionUtils.Vector3_z_set
    __swig_getmethods__["z"] = _WowInteractionUtils.Vector3_z_get
    if _newclass:
        z = _swig_property(_WowInteractionUtils.Vector3_z_get, _WowInteractionUtils.Vector3_z_set)

    def __init__(self, *args):
        this = _WowInteractionUtils.new_Vector3(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def __add__(self, right):
        return _WowInteractionUtils.Vector3___add__(self, right)

    def __sub__(self, right):
        return _WowInteractionUtils.Vector3___sub__(self, right)

    def __mul__(self, right):
        return _WowInteractionUtils.Vector3___mul__(self, right)

    def __eq__(self, right):
        return _WowInteractionUtils.Vector3___eq__(self, right)

    def __ne__(self, right):
        return _WowInteractionUtils.Vector3___ne__(self, right)
    __swig_destroy__ = _WowInteractionUtils.delete_Vector3
    __del__ = lambda self: None
Vector3_swigregister = _WowInteractionUtils.Vector3_swigregister
Vector3_swigregister(Vector3)
cvar = _WowInteractionUtils.cvar
PI = cvar.PI

class Position(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Position, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Position, name)
    __repr__ = _swig_repr
    __swig_setmethods__["coords"] = _WowInteractionUtils.Position_coords_set
    __swig_getmethods__["coords"] = _WowInteractionUtils.Position_coords_get
    if _newclass:
        coords = _swig_property(_WowInteractionUtils.Position_coords_get, _WowInteractionUtils.Position_coords_set)
    __swig_setmethods__["rotation"] = _WowInteractionUtils.Position_rotation_set
    __swig_getmethods__["rotation"] = _WowInteractionUtils.Position_rotation_get
    if _newclass:
        rotation = _swig_property(_WowInteractionUtils.Position_rotation_get, _WowInteractionUtils.Position_rotation_set)

    def __init__(self, *args):
        this = _WowInteractionUtils.new_Position(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _WowInteractionUtils.delete_Position
    __del__ = lambda self: None
Position_swigregister = _WowInteractionUtils.Position_swigregister
Position_swigregister(Position)

# This file is compatible with both classic and new-style classes.


