# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_WowObject', [dirname(__file__)])
        except ImportError:
            import _WowObject
            return _WowObject
        if fp is not None:
            try:
                _mod = imp.load_module('_WowObject', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _WowObject = swig_import_helper()
    del swig_import_helper
else:
    import _WowObject
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Vector3(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vector3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vector3, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _WowObject.Vector3_x_set
    __swig_getmethods__["x"] = _WowObject.Vector3_x_get
    if _newclass:
        x = _swig_property(_WowObject.Vector3_x_get, _WowObject.Vector3_x_set)
    __swig_setmethods__["y"] = _WowObject.Vector3_y_set
    __swig_getmethods__["y"] = _WowObject.Vector3_y_get
    if _newclass:
        y = _swig_property(_WowObject.Vector3_y_get, _WowObject.Vector3_y_set)
    __swig_setmethods__["z"] = _WowObject.Vector3_z_set
    __swig_getmethods__["z"] = _WowObject.Vector3_z_get
    if _newclass:
        z = _swig_property(_WowObject.Vector3_z_get, _WowObject.Vector3_z_set)

    def __init__(self, *args):
        this = _WowObject.new_Vector3(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def __add__(self, right):
        return _WowObject.Vector3___add__(self, right)

    def __sub__(self, right):
        return _WowObject.Vector3___sub__(self, right)

    def __mul__(self, right):
        return _WowObject.Vector3___mul__(self, right)

    def __eq__(self, right):
        return _WowObject.Vector3___eq__(self, right)

    def __ne__(self, right):
        return _WowObject.Vector3___ne__(self, right)
    __swig_destroy__ = _WowObject.delete_Vector3
    __del__ = lambda self: None
Vector3_swigregister = _WowObject.Vector3_swigregister
Vector3_swigregister(Vector3)
cvar = _WowObject.cvar
PI = cvar.PI

class Position(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Position, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Position, name)
    __repr__ = _swig_repr
    __swig_setmethods__["coords"] = _WowObject.Position_coords_set
    __swig_getmethods__["coords"] = _WowObject.Position_coords_get
    if _newclass:
        coords = _swig_property(_WowObject.Position_coords_get, _WowObject.Position_coords_set)
    __swig_setmethods__["rotation"] = _WowObject.Position_rotation_set
    __swig_getmethods__["rotation"] = _WowObject.Position_rotation_get
    if _newclass:
        rotation = _swig_property(_WowObject.Position_rotation_get, _WowObject.Position_rotation_set)

    def __init__(self, *args):
        this = _WowObject.new_Position(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _WowObject.delete_Position
    __del__ = lambda self: None
Position_swigregister = _WowObject.Position_swigregister
Position_swigregister(Position)

class Guid128(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Guid128, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Guid128, name)
    __repr__ = _swig_repr
    __swig_setmethods__["low"] = _WowObject.Guid128_low_set
    __swig_getmethods__["low"] = _WowObject.Guid128_low_get
    if _newclass:
        low = _swig_property(_WowObject.Guid128_low_get, _WowObject.Guid128_low_set)
    __swig_setmethods__["high"] = _WowObject.Guid128_high_set
    __swig_getmethods__["high"] = _WowObject.Guid128_high_get
    if _newclass:
        high = _swig_property(_WowObject.Guid128_high_get, _WowObject.Guid128_high_set)

    def __init__(self):
        this = _WowObject.new_Guid128()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _WowObject.delete_Guid128
    __del__ = lambda self: None
Guid128_swigregister = _WowObject.Guid128_swigregister
Guid128_swigregister(Guid128)


_WowObject.ITEM_swigconstant(_WowObject)
ITEM = _WowObject.ITEM

_WowObject.CONTAINER_swigconstant(_WowObject)
CONTAINER = _WowObject.CONTAINER

_WowObject.UNIT_swigconstant(_WowObject)
UNIT = _WowObject.UNIT

_WowObject.PLAYER_swigconstant(_WowObject)
PLAYER = _WowObject.PLAYER

_WowObject.GAMEOBJECT_swigconstant(_WowObject)
GAMEOBJECT = _WowObject.GAMEOBJECT

_WowObject.DYNAMICOBJECT_swigconstant(_WowObject)
DYNAMICOBJECT = _WowObject.DYNAMICOBJECT

_WowObject.CORPSE_swigconstant(_WowObject)
CORPSE = _WowObject.CORPSE

_WowObject.AiGroup_swigconstant(_WowObject)
AiGroup = _WowObject.AiGroup

_WowObject.AreaTrigger_swigconstant(_WowObject)
AreaTrigger = _WowObject.AreaTrigger
class WowObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, WowObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, WowObject, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _WowObject.delete_WowObject
    __del__ = lambda self: None

    def SetBase(self, base):
        return _WowObject.WowObject_SetBase(self, base)

    def GetBase(self):
        return _WowObject.WowObject_GetBase(self)

    def GetType(self, refresh=False):
        return _WowObject.WowObject_GetType(self, refresh)

    def GetID(self, refresh=False):
        return _WowObject.WowObject_GetID(self, refresh)

    def GetGuid(self, refresh=False):
        return _WowObject.WowObject_GetGuid(self, refresh)

    def GetName(self, refresh=False):
        return _WowObject.WowObject_GetName(self, refresh)
    __swig_getmethods__["GetType_Static"] = lambda x: _WowObject.WowObject_GetType_Static
    if _newclass:
        GetType_Static = staticmethod(_WowObject.WowObject_GetType_Static)

    def GetPosition(self):
        return _WowObject.WowObject_GetPosition(self)
WowObject_swigregister = _WowObject.WowObject_swigregister
WowObject_swigregister(WowObject)

def WowObject_GetType_Static(base):
    return _WowObject.WowObject_GetType_Static(base)
WowObject_GetType_Static = _WowObject.WowObject_GetType_Static

# This file is compatible with both classic and new-style classes.


